### ISSUE TITLE
Thank you for this series!

### ISSUE THREAD

**Issue by Aion-github** [thaterikperson/elmseeds#2]
Hy Erik 😄 , just wanted to let you know how much I appreciate your content.  💯 x 👍 
Please post this series of videos on YouTube also. The content covered here is very very good - and will be much easier for people to find it once the google algorithms picks it up.  There is nothing this valuable out there right now. Most of the videos are just introductions to elm in different conferences.. not useful once you pass the getting started phase - and decide that you want to go deeper into elm. 

For a elm beginner - your content is the missing link between just starting out with elm-tutorial page - and being able to fully navigate the GitHub docks and do whatever you want - as an experienced user. 

I can't express how much time i spend trying to figure out how things are wired - from a high level conceptual perspective.. picking the right functions .. wiring things up .. etc.

A 10 minute video like yours gives immediately a very clear picture of what i need to do next. For example - i was wondering around, trying to figure out how to do a native module - and now i'm confident that i can get my `elm-pdf` package done by tonight.

So glad i found your website. Best of luck! 😄

**Comment by thaterikperson** [comment]
Thank you for the kind words. If I ever need motivation to produce another video, I'll read this and be back to work in no time!
