### ISSUE TITLE
Access denied for video source of episode 36

### ISSUE THREAD

**Issue by andys8** [thaterikperson/elmseeds#3]
When trying to watch the current episode 36 you get an `Access denied` error. Probably S3 permissions config.

https://elmseeds.thaterikperson.com/window-resizing

```xml
<Error>
  <Code>
    AccessDenied
  </Code>
  <Message>
    Access Denied
  </Message>
  <RequestId>
    6CA2890562A811FF
  </RequestId>
  <HostId>
    qMPtvhjZCW5k8ctRQKgs8ZkpvndgUvgJADjzADcUGqWiOXgQugimGw3JwnKlLd+fs7Tz80urIO8=
  </HostId>
</Error>
```

<img width="955" alt="screen shot 2017-06-03 at 13 47 42" src="https://cloud.githubusercontent.com/assets/13085980/26753275/50270544-4863-11e7-8174-f357dc8dbb1b.png">

By the way: Awesome videos, glad I found them 👍

**Comment by thaterikperson** [comment]
Thanks for letting me know. Should be working now.
